### ISSUE TITLE
Encoding type for anndata objects is "AnnData", which isn't how anndata does it

### ISSUE THREAD

**Issue by ivirshup** [scverse/mudata#12]
Compatibility issue, was just making some little examples for the anndata release candidate (out now btw), and noticed a discrepancy in how we label anndata objects. 

In anndata, I've labelled `AnnData` objects as `encoding-type: "anndata"`, since every other encoded type has a lowercase name. Here, it's `"AnnData"`.

We should probably agree on one. Thoughts?

**Comment by ivirshup** [comment]
My proposal is that we normalize to lowercase, but I'll register the capitalized `"AnnData"` for `encoding-version: "0.1.0"`.

**Comment by gtca** [comment]
I am fine with going with the lowercase.
