### ISSUE TITLE
Link to AnnData file format from MuData file format

### ISSUE THREAD

**Issue by ivirshup** [scverse/mudata#19]
Hey, was just looking at the mudata file format docs. I think it would be useful to link to the [relevant docs for anndata here](https://anndata.readthedocs.io/en/latest/fileformat-prose.html).

**Comment by gtca** [comment]
Thanks, this is now linked in the [io/output](https://mudata.readthedocs.io/en/latest/io/output.html). Might be worth expanding a bit beyond just a link though.

**Comment by gtca** [comment]
There's also a new spec page to build on that anndata spec page: https://mudata.readthedocs.io/en/latest/io/spec.html.
