### ISSUE TITLE
Enable propagating obs columns to individual modalities

### ISSUE THREAD

**Issue by mffrank** [scverse/mudata#2]
There is currently no way of propagating columns in the global .obs slot of a mudata object to all modalities. This could be a useful feature, e.g. when you have metadata that you want to be present in all modalites (for example when unimodal methods depend on that metadata). 

I think the easiest solution would be to have a mdata.propagate_obs() method that looks through the columns of the mudata.obs table and writes columns not currently present in the individual modalites to their respective .obs in 2 ways:
- columns without without a `modname:` prefix are written to all modalities
- columns with `modname:xxx` are written to the .obs of `modname`

This would enable something like this:
```
mdata.obs.merge(metadata)
mdata.propagate_obs()
```

**Comment by gtca** [comment]
This is now implemented with the pull/push interface in #56
