### ISSUE TITLE
1.2.1 patch release

### ISSUE THREAD

**Issue by jjhong922** [scverse/mudata#23]
**Describe the bug**
No official release for an existing fix on master (https://github.com/scverse/mudata/commit/c3bf23cf1002433641eff9abc6505f9fb9dd6139).

**Additional context**
Would like to add an official release as a dependency for the next minor release of scvi-tools!

CC @adamgayoso

**Comment by gtca** [comment]
Has been closed by b1696c72716ccb15a9be6c2b734f976fe7b383bb.
