### ISSUE TITLE
len

### ISSUE THREAD

**Issue by rogershijin** [scverse/mudata#26]
Is there a reason `MuData` doesn't support `len`?

And if not would you consider adding some subclass that does?  For example,

```
class MuDataWithLen(MuData):
    
    def __len__(self):
        try:
            return self._len
        except:
            self._len = min(len(mod) for mod in self.mod.values())
            return self._len
```

Thanks a lot!

**Comment by gtca** [comment]
Hey @rogershijin, thanks for the feedback, no particular reason but that raises an interesting question: should it be `n_mod` or `n_obs` as the length?
I would expect `len(object)` to match `object.shape[0]`, and currently the shape of MuData is `(n_obs, n_var)`.

**Comment by rogershijin** [comment]
Thanks for getting back to me! Yea I think for me also it is more intuitive for this to be `n_obs`.

**Comment by ivirshup** [comment]
@gtca I'm not sure it makes sense for something to have `__len__` without `__iter__`. Also defining `__len__` implicitly defines `__bool__`.

**Comment by gtca** [comment]
@ivirshup maybe but [see anndata](https://github.com/scverse/anndata/blob/cc3ba6f29ca2de6e92b2468cdbec0a418d6f7478/anndata/_core/anndata.py#L1280).

**Comment by ivirshup** [comment]
I'm not sure anndata should have `len` either 😅

**Comment by ivirshup** [comment]
I think it needs some consideration of why you want the length, and what it should be consistent with. I do think if it were defined `n_obs` makes the most sense, but accessing `n_obs` or `shape` seems like probably the better approach.

**Comment by gtca** [comment]
I think it's ok to expect objects that have `.shape` to have their length defined as `.shape[0]`.

Practically, for the workflows as in scanpy/muon, one should rather use `.n_obs` as [explicit is better than implicit](https://peps.python.org/pep-0020/).

**Comment by rogershijin** [comment]
I should've mentioned this in the issue description, but on the practical application side I was originally motivated to post this because I couldn't use a PyTorch dataloader to batch load a MuData object without `__len__` being defined.
