### ISSUE TITLE
More AI/ML support?

### ISSUE THREAD

**Issue by amdqiao** [scverse/mudata#34]
Since many ML packages support AnnData format already, will MuData developers consider reaching out to ML package developers to make more ML packages load MuData as input? Thanks!

**Comment by gtca** [comment]
@amdqiao Thanks for the question! Are there particular applications or scenarios that would benefit from supporting MuData the most, in your opinion? 

As @Zethson mentioned, [there's MuData support](https://docs.scvi-tools.org/en/stable/search.html?q=MuData) for some multimodal models in scvi-tools. Newly developed models for single-cell multi-omics are hopefully supporting MuData straightaway — and we're happy to see what we can do from our side to make MuData support more abundant.

**Comment by amdqiao** [comment]
Yes, I've checked the scvi-tools and found it a useful tool. However, it will be even better if MuData can be supported as the input format for popular ML packages such as scikit-learn.
