### ISSUE TITLE
allow `backup_url` for read functions in MuData

### ISSUE THREAD

**Issue by AnnaChristina** [scverse/mudata#45]
For convenient file loading from back-up URLs would be great to have a similar argument as in `scanpy.read` that allows reading files from backup URLs which retrieves the file from an URL if not present on disk.

**Comment by grst** [comment]
I would prefer to see [pooch](https://github.com/fatiando/pooch) being used in such cases instead.

Here's an example how it can be used in tutorials: https://scverse-tutorials.readthedocs.io/en/latest/notebooks/basic-scrna-tutorial.html

**Comment by AnnaChristina** [comment]
thanks! closing this, was mainly interested in using this for the book but will keep things then consistent with your recommendation.
