### ISSUE TITLE
Add support for AnnData 0.10.0

### ISSUE THREAD

**Issue by martinkim0** [scverse/mudata#59]
**Is your feature request related to a problem? Please describe.**
The release candidate for AnnData 0.10.0 is out now - it would be great if the changes could be tested out here since we're looking to add support for it too in scvi-tools.

**Describe the solution you'd like**
Known bugs:
- `mudata._core.io._read_h5mu_mod` should not pass in `dtype` to `AnnData.__init__`

**Comment by gtca** [comment]
Hey Martin,

There's https://github.com/scverse/mudata/pull/53 that implements this as part of the `0.3` release.
That's the next planned release, which also comes with many other changes. That should be alright especially considering the `dtype` change will probably not land in `0.10` after all (https://github.com/scverse/anndata/issues/1137).

Does that sound reasonable to you?

**Comment by martinkim0** [comment]
Ah got it, was not aware of that! Sounds good
