### ISSUE TITLE
RecursionError when constructing an MuData object

### ISSUE THREAD

**Issue by aksarkar** [scverse/mudata#62]
Constructing an `MuData` object from a 10X formatted h5 file fails due to a `RecursionError`.

The following minimal example uses the 10X provided data set https://cf.10xgenomics.com/samples/cell-arc/2.0.0/10k_PBMC_Multiome_nextgem_Chromium_X/10k_PBMC_Multiome_nextgem_Chromium_X_raw_feature_bc_matrix.h5

```python
import scanpy as sc
import mudata

temp = sc.read_10x_h5('10k_PBMC_Multiome_nextgem_Chromium_Controller_raw_feature_bc_matrix.h5', gex_only=False)
target = {
    'rna': 'Gene Expression',
    'atac': 'Peaks',}
dat = mudata.MuData({
    k: temp[:,temp.var['feature_types'] == target[k]]
    for k in target})

```

and produces [the attached backtrace](https://github.com/scverse/mudata/files/13284097/backtrace.txt)

All packages were installed on an Amazon EC2 instance running Amazon Linux 2
from conda-forge via mamba.

- anndata=0.10.2=pyhd8ed1ab_0
- mudata=0.2.3=pyhd8ed1ab_0
- python=3.9.18=h0755675_0_cpython
- scanpy=1.9.5=pyhd8ed1ab_0

**Comment by ilia-kats** [comment]
I think this is because you are trying to create a MuData object from AnnData views instead of real AnnData objects. Try this:
```python
import scanpy as sc
import mudata

temp = sc.read_10x_h5('10k_PBMC_Multiome_nextgem_Chromium_Controller_raw_feature_bc_matrix.h5', gex_only=False)
target = {
    'rna': 'Gene Expression',
    'atac': 'Peaks',}
dat = mudata.MuData({
    k: temp[:,temp.var['feature_types'] == target[k]].copy()
    for k in target})
```

**Comment by aksarkar** [comment]
Your modification worked. Is there a way to check for this in mudata and throw an exception?

**Comment by aksarkar** [comment]
It seems that this is a bug in scanpy or anndata rather than mudata, since the following code also throws a RecursionError:

```python
import scanpy as sc

dat = sc.read_10x_h5('10k_PBMC_Multiome_nextgem_Chromium_Controller_raw_feature_bc_matrix.h5', gex_only=True)
assert not dat.is_view
dat.obs['0'] = 0
```

**Comment by grst** [comment]
Pandas 2.1.2 broke the view behavior in AnnData, see https://github.com/scverse/anndata/issues/1210

For now, please downgrade pandas to 2.1.1.

**Comment by aksarkar** [comment]
Reverting pandas to 2.1.1 fixed the issue. Thanks!
