### ISSUE TITLE
MuData is incompatible with AnnData v0.10.9

### ISSUE THREAD

**Issue by canergen** [scverse/mudata#77]
Import broken with AnnData version 0.10.9

**System**
 - OS: Ubuntu
 - 3.9
 -AnnData 0.10.9

```
  File "/home/cane/.local/share/hatch/env/virtual/scvi-tools/E5IuCX_W/scvi-tools/lib/python3.12/site-packages/mudata/_core/mudata.py", line 18, in <module>
    from anndata._core.aligned_mapping import (
ImportError: cannot import name 'AlignedViewMixin' from 'anndata._core.aligned_mapping' (/home/cane/.local/share/hatch/env/virtual/scvi-tools/E5IuCX_W/scvi-tools/lib/python3.12/site-packages/anndata/_core/aligned_mapping.py). Did you mean: 'AlignedView'?
```

**Comment by ilan-gold** [comment]
Before looking ito this, I would like to point out that this is not part of our public API

**Comment by gtca** [comment]
@ilan-gold, [there has been one already](https://github.com/scverse/mudata/blob/main/.github/workflows/dev.yml) that pulls the version from https://github.com/scverse/anndata.

**Comment by ilan-gold** [comment]
> @ilan-gold, [there has been one already](https://github.com/scverse/mudata/blob/main/.github/workflows/dev.yml) that pulls the version from https://github.com/scverse/anndata.

Great! I looked into this, but the issue isn't just exporting.  Our API also changed, so just re-exporting hte `AxisArraysView = AxisArrays` doesn't seem to solve this
